sudo: required

services:
  - docker

before_install:
  - docker pull pondthaitay/build-tools-android
  - docker run pondthaitay/build-tools-android
  - docker ps -a

script:
  - docker run -it -v "$HOME/.gradle":/root/.gradle -v $(pwd):/opt/workspace pondthaitay/build-tools-android fastlane build

