sudo: required

language : android

services:
  - docker

before_install:
  - docker pull pondthaitay/build-tools-android
  - docker run pondthaitay/build-tools-android
  - docker ps -a

script:
  - docker run -it --rm echo ${PWD} -v "$PWD" fastlane -v
