sudo: required

services:
  - docker

before_install:
  - docker pull pondthaitay/build-tools-android
  - docker run pondthaitay/build-tools-android
  - docker ps -a

script:
  - docker build pondthaitay/build-tools-android
