sudo: required

language: android

env:
  global: 
    - IMAGE_NAME=pondthaitay/build-tools-android

services:
  - docker

# before_cache:
#   - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/docker

before_install:
  - docker pull ${IMAGE_NAME} || true
  - docker run ${IMAGE_NAME}
  - docker ps -a

# before_script :
  # - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

script:
  - docker build --cache-from ${IMAGE_NAME}
  - docker run -it -v "$HOME/.gradle":/root/.gradle -v $(pwd):/opt/workspace "${IMAGE_NAME}" fastlane build