sudo: required

language: bash

env:
  global: 
    - IMAGE_NAME=pondthaitay/build-tools-android

services:
  - docker

before_script :
  - docker pull "$IMAGE_NAME" || true
  - docker save docker/"$IMAGE_NAME" | gzip > docker/"$IMAGE_NAME".tar.gz

after_script:
  - docker images

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
 - docker

script:
  - docker build --pull --cache-from "${IMAGE_NAME}"
  - docker run -it -v "$HOME/.gradle":/root/.gradle -v $(pwd):/opt/workspace "${IMAGE_NAME}" fastlane build