sudo: required

language: android

jdk: oraclejdk8

services:
  - docker

before_install:
  - docker pull pondthaitay/build-tools-android
  - docker ps -a
  - docker run pondthaitay/build-tools-android
  - yes | sdkmanager "platforms;android-26

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
    - ./gradlew clean build jacocoDebugReport