sudo: required

services:
  - docker

before_install:
  - docker pull pondthaitay/build-tools-android
  - docker run pondthaitay/build-tools-android
  - docker ps -a

script:
  - docker run -it --privileged --volume=$(pwd):/opt/workspace pondthaitay/build-tools-android fastlane build
