sudo: required

language: android

services:
  - docker

install :
  - docker pull pondthaitay/build-tools-android
  - docker save docker/pondthaitay/build-tools-android | gzip > docker/pondthaitay/build-tools-android.tar.gz
  - docker run pondthaitay/build-tools-android
  - docker ps -a

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
 - docker

before_script:
- gzip -dc docker/pondthaitay/build-tools-android.tar.gz | docker load

script:
  - docker run -it -v "$HOME/.gradle":/root/.gradle -v $(pwd):/opt/workspace pondthaitay/build-tools-android fastlane build