version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          docker build .    
      - run:
          name: Build application Docker image	
          command: |	
            docker build --cache-from=app -t app .
      - run:
          name: Run tests
          command: |
            fastlane -v