version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: pondthaitay/build-tools-android
    environment:
      JVM_OPTS: -Xmx3200m
    dependencies:
      cache_directories:
        - "~/docker"
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build .
      # - restore_cache:
      #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      # - save_cache:
      #     paths:
      #       - ~/.gradle
      #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      # - run:
      #     name: Fastlane Build Application
      #     command: fastlane build
      # - store_artifacts:
      #     path: app/build/reports
      #     destination: reports
      # - store_test_results:
      #     path: app/build/test-results